version: '2'
services:
  mongodb:
    image: mongo:6.0.8
    ports:
      - "27017:27017"
  party-mode-backend:
    build:
      context: backend
    environment:
      NODE_ENV: ${PARTYMODE_BACKEND_NODE_ENV}
      PORT: ${PARTYMODE_BACKEND_PORT}
      LOG_LEVEL: ${PARTYMODE_BACKEND_LOG_LEVEL}
      CORS_ORIGIN: ${PARTYMODE_BACKEND_CORS_ORIGIN}
      SESSION_SECRET: ${PARTYMODE_BACKEND_SESSION_SECRET}
      SESSION_MAX_AGE: ${PARTYMODE_BACKEND_SESSION_MAX_AGE}
      SESSION_COLLECTIONNAME: ${PARTYMODE_BACKEND_SESSION_COLLECTIONNAME}
      MONGODB_CONNECTIONSTRING: ${PARTYMODE_BACKEND_MONGODB_CONNECTIONSTRING}
      MONGODB_DATABASENAME: ${PARTYMODE_BACKEND_MONGODB_DATABASENAME}
      AUTH_GOOGLE_CLIENT_ID: ${PARTYMODE_BACKEND_AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${PARTYMODE_BACKEND_AUTH_GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb