version: '3.8'
services:
  mongodb:
    image: mongo:6.0.8
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017',priority:1}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
  mongo-seed:
    image: mongo:6.0.8
    links:
      - mongodb
    volumes:
      - ./docker/mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
  party-mode-backend:
    build:
      context: backend
    environment:
      NODE_ENV: ${PARTYMODE_BACKEND_NODE_ENV}
      PORT: ${PARTYMODE_BACKEND_PORT}
      LOG_LEVEL: ${PARTYMODE_BACKEND_LOG_LEVEL}
      CORS_ORIGIN: ${PARTYMODE_BACKEND_CORS_ORIGIN}
      SESSION_SECRET: ${PARTYMODE_BACKEND_SESSION_SECRET}
      SESSION_MAX_AGE: ${PARTYMODE_BACKEND_SESSION_MAX_AGE}
      SESSION_COLLECTIONNAME: ${PARTYMODE_BACKEND_SESSION_COLLECTIONNAME}
      MONGODB_CONNECTIONSTRING: ${PARTYMODE_BACKEND_MONGODB_CONNECTIONSTRING}
      MONGODB_DATABASENAME: ${PARTYMODE_BACKEND_MONGODB_DATABASENAME}
      AUTH_GOOGLE_CLIENT_ID: ${PARTYMODE_BACKEND_AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${PARTYMODE_BACKEND_AUTH_GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  party-mode-frontend:
    build:
      context: frontend
    environment:
      VITE_BACKEND_BASE_URI: http://party-mode-backend:8080
    ports:
      - "80:80"
    depends_on:
      - party-mode-backend